# Generated by Django 4.2.30 on 2026-05-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction_created_at_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='next_occurence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='api.user')),
            ],
        ),
    ]
